import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)

GPIO.setup(7, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)

GPIO.setup(15, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)

GPIO.setup(35, GPIO.OUT)
GPIO.setup(36, GPIO.OUT)
GPIO.setup(38, GPIO.OUT)
GPIO.setup(40, GPIO.OUT)

GPIO.setup(29, GPIO.OUT)
GPIO.setup(31, GPIO.OUT)
GPIO.setup(32, GPIO.OUT)
GPIO.setup(33, GPIO.OUT)

GPIO.setup(7, GPIO.LOW)
GPIO.setup(11, GPIO.LOW)
GPIO.setup(12, GPIO.LOW)
GPIO.setup(13, GPIO.LOW)
GPIO.setup(15, GPIO.LOW)
GPIO.setup(16, GPIO.LOW)
GPIO.setup(18, GPIO.LOW)
GPIO.setup(22, GPIO.LOW)
GPIO.setup(35, GPIO.LOW)
GPIO.setup(36, GPIO.LOW)
GPIO.setup(38, GPIO.LOW)
GPIO.setup(40, GPIO.LOW)
GPIO.setup(29, GPIO.LOW)
GPIO.setup(31, GPIO.LOW)
GPIO.setup(32, GPIO.OUT)
GPIO.setup(33, GPIO.OUT)
time.sleep(1)
while(True):
	GPIO.output(7, GPIO.HIGH)
	GPIO.output(35, GPIO.HIGH)
	GPIO.output(18, GPIO.HIGH)
	GPIO.output(22, GPIO.HIGH)
	GPIO.output(32, GPIO.HIGH)
	GPIO.output(33, GPIO.HIGH)
	time.sleep(5)
        GPIO.output(18, GPIO.LOW)
        GPIO.output(22, GPIO.LOW)
        GPIO.output(32, GPIO.LOW)
        GPIO.output(33, GPIO.LOW)


	GPIO.output(16, GPIO.HIGH)
	GPIO.output(31, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(31, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(16, GPIO.HIGH)
	GPIO.output(31, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(31, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(16, GPIO.HIGH)
	GPIO.output(31, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(31, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(16, GPIO.HIGH)
	GPIO.output(31, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(31, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(16, GPIO.HIGH)
	GPIO.output(31, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(31, GPIO.LOW)
	time.sleep(0.5)

	GPIO.output(7, GPIO.LOW)
	GPIO.output(35, GPIO.LOW)


	GPIO.output(15, GPIO.HIGH)
	GPIO.output(29, GPIO.HIGH)
	GPIO.output(12, GPIO.HIGH)
	GPIO.output(13, GPIO.HIGH)
	GPIO.output(38, GPIO.HIGH)
	GPIO.output(40, GPIO.HIGH)
	time.sleep(5)
        GPIO.output(12, GPIO.LOW)
        GPIO.output(13, GPIO.LOW)
        GPIO.output(38, GPIO.LOW)
        GPIO.output(40, GPIO.LOW)

	
	GPIO.output(11, GPIO.HIGH)
	GPIO.output(36, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(11, GPIO.LOW)
	GPIO.output(36, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(11, GPIO.HIGH)
	GPIO.output(36, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(11, GPIO.LOW)
	GPIO.output(36, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(11, GPIO.HIGH)
	GPIO.output(36, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(11, GPIO.LOW)
	GPIO.output(36, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(11, GPIO.HIGH)
	GPIO.output(36, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(11, GPIO.LOW)
	GPIO.output(36, GPIO.LOW)
	time.sleep(0.5)
	GPIO.output(11, GPIO.HIGH)
	GPIO.output(36, GPIO.HIGH)
	time.sleep(0.5)
	GPIO.output(11, GPIO.LOW)
	GPIO.output(36, GPIO.LOW)
	time.sleep(0.5)

	GPIO.output(15, GPIO.LOW)
	GPIO.output(29, GPIO.LOW)
GPIO.cleanup();

